name: DeployToServer

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PREVIEW_HOST }}
          username: ${{ secrets.PREVIEW_USER }}
          port: ${{ secrets.PREVIEW_PORT }}
          password: ${{ secrets.PREVIEW_PASS }}
          script: ${{ secrets.PREVIEW_SCRIPT }}
